# Generated by Django 6.0.7 on 2026-07-17 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Nome de usuário só pode ter letras, números e os caracteres _ . $ ! ? - (sem espaços, aspas ou <>).', regex='^[A-Za-z0-9_.$!?-]+$')]),
        ),
    ]
