# Generated by Django 6.0.7 on 2026-07-17 02:35

import shared.validators.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[shared.validators.common.validate_username_format]),
        ),
    ]
