# Generated by Django 6.0.7 on 2026-07-14 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenges', to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anon_token', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost')], default='playing', max_length=10)),
                ('attempts_used', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=1000)),
                ('hints_used', models.JSONField(default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.dailychallenge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('clues', models.JSONField(default=dict)),
                ('guessed_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.gamesession')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('challenge', 'user'), name='uniq_user_challenge'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_token__isnull', False)), fields=('challenge', 'anon_token'), name='uniq_anon_challenge'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anon_token__isnull', True), ('user__isnull', False)), models.Q(('anon_token__isnull', False), ('user__isnull', True)), _connector='OR'), name='session_user_xor_anon'),
        ),
        migrations.AddConstraint(
            model_name='guessattempt',
            constraint=models.UniqueConstraint(fields=('session', 'attempt_number'), name='uniq_session_attempt'),
        ),
    ]
