# Generated by Django 6.0.7 on 2026-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenge',
            name='image_source',
            field=models.CharField(choices=[('poster', 'Poster'), ('backdrop', 'Backdrop')], default='poster', max_length=10),
        ),
    ]
