# Generated by Django 6.0.7 on 2026-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_dailychallenge_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenge',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
