# Generated by Django 6.0.7 on 2026-07-18 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_dailychallenge_image_path'),
        ('movies', '0002_movie_backdrop_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cast_challenges', to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CastSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anon_token', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost')], default='playing', max_length=10)),
                ('attempts_used', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=1000)),
                ('guesses', models.JSONField(default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.castchallenge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('challenge', 'user'), name='uniq_cast_user_challenge'), models.CheckConstraint(condition=models.Q(models.Q(('anon_token__isnull', True), ('user__isnull', False)), models.Q(('anon_token__isnull', False), ('user__isnull', True)), _connector='OR'), name='cast_session_user_xor_anon')],
            },
        ),
    ]
