# Generated by Django 6.0.7 on 2026-07-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tmdb_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, default='', max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('origin_country', models.CharField(blank=True, default='', max_length=2)),
                ('continent', models.CharField(blank=True, default='', max_length=2)),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('top_cast', models.JSONField(default=list)),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, default='', max_length=255)),
                ('popularity', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
