# Generated by Django 6.0.7 on 2026-07-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150, unique=True)),
                ('weekly_points', models.PositiveIntegerField(default=0)),
                ('monthly_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('weekly_streak', models.PositiveSmallIntegerField(default=0)),
                ('monthly_streak', models.PositiveSmallIntegerField(default=0)),
                ('best_streak', models.PositiveSmallIntegerField(default=0)),
                ('streak_achieved_on', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
