# Generated by Django 6.0.7 on 2026-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_rename_mock_players_to_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockplayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
